# Generated by Django 3.1.2 on 2020-11-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201126_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='email_reciver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
