# Generated by Django 3.1.12 on 2021-06-02 11:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_email_reciver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='selection_1_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='selection_1_image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='selection_2_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='selection_2_image'),
        ),
    ]
