# Generated by Django 3.1.12 on 2021-06-02 12:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210602_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='title_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='title_image'),
        ),
    ]
