# Generated by Django 2.2.24 on 2021-06-02 14:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailcloudinary.blocks
import wagtailcloudinary.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210602_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=wagtailcloudinary.fields.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider',
            field=wagtail.core.fields.StreamField([('image', wagtailcloudinary.blocks.CloudinaryImageBlock()), ('link', wagtail.core.blocks.CharBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='selection_1_image',
            field=wagtailcloudinary.fields.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='selection_1_image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='selection_2_image',
            field=wagtailcloudinary.fields.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='selection_2_image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_image',
            field=wagtailcloudinary.fields.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='title_image'),
        ),
    ]
